ashby:
- aleph-alpha
- anyscale
- bolt
- cohere
- deepgram
- deepl
- elevenlabs
- helmholtzmunich
- juni
- klarna
- langchain
- langfuse
- lovable
- mistral
- parloa
- perplexity
- photoroom
- pigment
- runwayml
- scaleway
- spotify
- togetherai
- weightsandbiases
comeet: []
greenhouse:
- aboutyou
- adjust
- adobe
- adyen
- affirm
- airbnb
- airbyte
- amazon
- amd
- anduril
- anthropic
- apple
- asana
- atlassian
- auto1group
- block
- bookingcom
- box
- brex
- canva
- celonis
- check24
- chime
- cloudflare
- coinbase
- commercetools
- confluent
- contentful
- contentsquare
- coursera
- crowdstrike
- databricks
- datadog
- dbt-labs
- dbtlabs
- deliveryhero
- discord
- doctolib
- doordash
- dropbox
- duolingo
- elastic
- eventbrite
- expedia
- figma
- fivetran
- flink
- flix
- getyourguide
- gitlab
- google
- gusto
- hashicorp
- hellofresh
- hubspot
- huggingface
- instacart
- intel
- intercom
- lattice
- linear
- lyft
- mercury
- messagebird
- meta
- microsoft
- mirakl
- mongodb
- n26
- notion
- nvidia
- okta
- omio
- openai
- palantirtechnologies
- personio
- picsart
- plaid
- qualcomm
- raisin
- ramp
- reddit
- revolut
- rippling
- robinhood
- scaleai
- shopify
- snap
- snowflake
- snowflakecomputing
- sofi
- solarisbank
- spotify
- spryker
- squareup
- stripe
- sumup
- taxfix
- ticketmaster
- tier
- traderepublic
- tripadvisor
- twilio
- uber
- vercel
- wayfair
- wise
- wolt
- zalando
- zendesk
lever:
- box
- coursera
- dropbox
- duolingo
- eventbrite
- okta
- palantir
- reddit
- shopify
- snap
- twilio
- verizonmedia
- wayfair
pinpoint:
- workwithus
recruitee:
- bunq
smartrecruiters:
- BoschGroup
- Continental
- DeliveryHero
teamtailor:
- bambuser.teamtailor.com
- einride.teamtailor.com
- epidemicsound.teamtailor.com
- karma.teamtailor.com
- mentimeter.teamtailor.com
- truecaller.teamtailor.com
- vinted.teamtailor.com
workable:
- huggingface
